# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  run:
    cmds:
      - cargo run -q
  watch:
    cmds:
      - cargo watch -x run
  build:
    cmds:
      - cargo build
  release:
    cmds:
      - cargo build --release
  docker-build:
    cmds:
      - docker build . -t graphql-rust-starter:latest
  docker-run:
    cmds:
      - docker run -p 4001:4001 --rm graphql-rust-starter:latest
    silent: true
